### ISSUE TITLE
does not work with poetry 1.0.0

### ISSUE THREAD

**Issue by chrispblink** [ChrisArgyle/pooetry#7]
When I run `pooetry` with the 1.0.0 `poetry` installed, I get this
```
chris.przybycien@MBP15-496 ~ $ poetry --version
Poetry version 1.0.0
chris.przybycien@MBP15-496 ~ $ pooetry --version
Traceback (most recent call last):
  File "/usr/local/bin/pooetry", line 10, in <module>
    sys.exit(main.main())
  File "/usr/local/lib/python3.7/site-packages/pooetry/main.py", line 99, in main
    poetry.console.main()
AttributeError: module 'poetry' has no attribute 'console'
chris.przybycien@MBP15-496 ~ $
```

**Comment by ChrisArgyle** [comment]
Fixed in PR #8
